// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package student

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StudentInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Grade                int32    `protobuf:"varint,2,opt,name=grade,proto3" json:"grade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentInfo) Reset()         { *m = StudentInfo{} }
func (m *StudentInfo) String() string { return proto.CompactTextString(m) }
func (*StudentInfo) ProtoMessage()    {}
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *StudentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentInfo.Unmarshal(m, b)
}
func (m *StudentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentInfo.Marshal(b, m, deterministic)
}
func (m *StudentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfo.Merge(m, src)
}
func (m *StudentInfo) XXX_Size() int {
	return xxx_messageInfo_StudentInfo.Size(m)
}
func (m *StudentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfo proto.InternalMessageInfo

func (m *StudentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfo) GetGrade() int32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

type GetStudentReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentReq) Reset()         { *m = GetStudentReq{} }
func (m *GetStudentReq) String() string { return proto.CompactTextString(m) }
func (*GetStudentReq) ProtoMessage()    {}
func (*GetStudentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{1}
}

func (m *GetStudentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentReq.Unmarshal(m, b)
}
func (m *GetStudentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentReq.Marshal(b, m, deterministic)
}
func (m *GetStudentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentReq.Merge(m, src)
}
func (m *GetStudentReq) XXX_Size() int {
	return xxx_messageInfo_GetStudentReq.Size(m)
}
func (m *GetStudentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentReq proto.InternalMessageInfo

func (m *GetStudentReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStudentReply struct {
	Student              *StudentInfo `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetStudentReply) Reset()         { *m = GetStudentReply{} }
func (m *GetStudentReply) String() string { return proto.CompactTextString(m) }
func (*GetStudentReply) ProtoMessage()    {}
func (*GetStudentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{2}
}

func (m *GetStudentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentReply.Unmarshal(m, b)
}
func (m *GetStudentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentReply.Marshal(b, m, deterministic)
}
func (m *GetStudentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentReply.Merge(m, src)
}
func (m *GetStudentReply) XXX_Size() int {
	return xxx_messageInfo_GetStudentReply.Size(m)
}
func (m *GetStudentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentReply proto.InternalMessageInfo

func (m *GetStudentReply) GetStudent() *StudentInfo {
	if m != nil {
		return m.Student
	}
	return nil
}

func init() {
	proto.RegisterType((*StudentInfo)(nil), "student.StudentInfo")
	proto.RegisterType((*GetStudentReq)(nil), "student.GetStudentReq")
	proto.RegisterType((*GetStudentReply)(nil), "student.GetStudentReply")
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00) }

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xcc, 0xb9,
	0xb8, 0x83, 0x21, 0x4c, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0xbd, 0x28, 0x31,
	0x25, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc2, 0x51, 0x52, 0xe6, 0xe2, 0x75, 0x4f,
	0x2d, 0x81, 0xea, 0x0d, 0x4a, 0x2d, 0xc4, 0xa6, 0x55, 0xc9, 0x91, 0x8b, 0x1f, 0x59, 0x51, 0x41,
	0x4e, 0xa5, 0x90, 0x1e, 0x17, 0xcc, 0x6e, 0xb0, 0x4a, 0x6e, 0x23, 0x11, 0x3d, 0x98, 0xd3, 0x90,
	0x1c, 0x12, 0x04, 0x53, 0x64, 0xe4, 0xc9, 0xc5, 0x0e, 0x15, 0x17, 0xb2, 0xe3, 0xe2, 0x42, 0x98,
	0x26, 0x24, 0x06, 0xd7, 0x87, 0xe2, 0x0e, 0x29, 0x09, 0xac, 0xe2, 0x05, 0x39, 0x95, 0x4e, 0xdc,
	0x51, 0x9c, 0x7a, 0xd6, 0x50, 0xc9, 0x24, 0x36, 0x70, 0x40, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x74, 0x84, 0x31, 0x76, 0x19, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Student service

type StudentClient interface {
	GetStudent(ctx context.Context, in *GetStudentReq, opts ...client.CallOption) (*GetStudentReply, error)
}

type studentClient struct {
	c           client.Client
	serviceName string
}

func NewStudentClient(serviceName string, c client.Client) StudentClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "student"
	}
	return &studentClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *studentClient) GetStudent(ctx context.Context, in *GetStudentReq, opts ...client.CallOption) (*GetStudentReply, error) {
	req := c.c.NewRequest(c.serviceName, "Student.GetStudent", in)
	out := new(GetStudentReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Student service

type StudentHandler interface {
	GetStudent(context.Context, *GetStudentReq, *GetStudentReply) error
}

func RegisterStudentHandler(s server.Server, hdlr StudentHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Student{hdlr}, opts...))
}

type Student struct {
	StudentHandler
}

func (h *Student) GetStudent(ctx context.Context, in *GetStudentReq, out *GetStudentReply) error {
	return h.StudentHandler.GetStudent(ctx, in, out)
}
